"""add constraints defaults and phase status

Revision ID: 2c2572ff4c03
Revises: e883a87f1d2f
Create Date: 2026-07-02 08:59:13.648389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2572ff4c03'
down_revision: Union[str, None] = 'e883a87f1d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_phases', sa.Column('status', sa.String(length=20), server_default='todo', nullable=False))
    op.create_index('uq_team_invitations_pending_per_user', 'team_invitations', ['team_id', 'invited_user_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_unique_constraint('uq_team_members_team_user', 'team_members', ['team_id', 'user_id'])
    # ### end Alembic commands ###

    # server-side defaults for existing columns (not auto-detected by Alembic)
    op.alter_column('teams', 'readiness_score', server_default=sa.text('0'))
    op.alter_column('teams', 'status', server_default='forming')
    op.alter_column('team_invitations', 'status', server_default='pending')
    op.alter_column('team_members', 'has_committed', server_default=sa.text('false'))
    op.alter_column('projects', 'status', server_default='accepted')
    op.alter_column('tasks', 'status', server_default='todo')

    # CHECK constraints restricting status/enum-like columns to their canonical values
    op.create_check_constraint('ck_users_availability', 'users', "availability IN ('part_time', 'full_time')")
    op.create_check_constraint(
        'ck_user_skills_proficiency_level', 'user_skills', "proficiency_level IN ('beginner', 'intermediate', 'advanced')"
    )
    op.create_check_constraint('ck_teams_status', 'teams', "status IN ('forming', 'active', 'completed')")
    op.create_check_constraint(
        'ck_team_invitations_status', 'team_invitations', "status IN ('pending', 'accepted', 'declined')"
    )
    op.create_check_constraint('ck_projects_status', 'projects', "status IN ('accepted', 'in_progress', 'completed')")
    op.create_check_constraint('ck_roadmap_phases_status', 'roadmap_phases', "status IN ('todo', 'in_progress', 'done')")
    op.create_check_constraint('ck_tasks_status', 'tasks', "status IN ('todo', 'in_progress', 'done')")


def downgrade() -> None:
    op.drop_constraint('ck_tasks_status', 'tasks', type_='check')
    op.drop_constraint('ck_roadmap_phases_status', 'roadmap_phases', type_='check')
    op.drop_constraint('ck_projects_status', 'projects', type_='check')
    op.drop_constraint('ck_team_invitations_status', 'team_invitations', type_='check')
    op.drop_constraint('ck_teams_status', 'teams', type_='check')
    op.drop_constraint('ck_user_skills_proficiency_level', 'user_skills', type_='check')
    op.drop_constraint('ck_users_availability', 'users', type_='check')

    op.alter_column('tasks', 'status', server_default=None)
    op.alter_column('projects', 'status', server_default=None)
    op.alter_column('team_members', 'has_committed', server_default=None)
    op.alter_column('team_invitations', 'status', server_default=None)
    op.alter_column('teams', 'status', server_default=None)
    op.alter_column('teams', 'readiness_score', server_default=None)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_members_team_user', 'team_members', type_='unique')
    op.drop_index('uq_team_invitations_pending_per_user', table_name='team_invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_column('roadmap_phases', 'status')
    # ### end Alembic commands ###
