"""add difficulty and technologies to project recommendations

Revision ID: 87e92adac3c5
Revises: 2c2572ff4c03
Create Date: 2026-07-13 06:23:09.178288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e92adac3c5'
down_revision: Union[str, None] = '2c2572ff4c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_recommendations', sa.Column('difficulty_level', sa.String(length=20), nullable=True))
    op.add_column('project_recommendations', sa.Column('required_technologies', postgresql.ARRAY(sa.String(length=100)), nullable=True))
    # ### end Alembic commands ###

    # CHECK constraint not auto-detected by Alembic (NULL rows predating this
    # migration pass the check automatically)
    op.create_check_constraint(
        'ck_project_recommendations_difficulty',
        'project_recommendations',
        "difficulty_level IN ('beginner', 'intermediate', 'advanced')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_project_recommendations_difficulty', 'project_recommendations', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_recommendations', 'required_technologies')
    op.drop_column('project_recommendations', 'difficulty_level')
    # ### end Alembic commands ###
